#!/bin/bash

###############
# PRIME2.1 is a predictor of MHC ligand displayed at the cell surface.
#
# PRIME requires MixMHCpred (version 3.0 or above) to be installed on your computer.
#
# PRIME2.1 can be used freely by academic groups for non-commercial purposes (see license).
# The product is provided free of charge, and, therefore, on an "as is"
#  basis, without warranty of any kind.
#
# FOR-PROFIT USERS
# If you plan to use PRIME (version 2.1) or any data provided with the script in any for-profit
# application, you are required to obtain a separate  license.
# To do so, please contact Nadette Bulgin (nbulgin@lcr.org) at the Ludwig Institute for  Cancer Research Ltd.
#
# If you use PRIME2.1 in a publication, please cite:
# Tadros et al. BioRxiv (2024).
#
# For the older version (PRIME2.0), please cite:
# Gfeller et al. Improved predictions of antigen presentation and TCR recognition with MixMHCpred2.2 and PRIME2.0 reveal potent SARS-CoV-2 CD8+ T-cell epitopes , Cell Systems (2023).
#
# For scientific questions, please contact David Gfeller (David.Gfeller@unil.ch)

# Copyright (2024) David Gfeller
############



# Get the absolute path to the directory containing the executable file
executable_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Get the absolute path to the directory containing the libraries
lib_path="$executable_dir/lib"

usage="Usage:PRIME -i INPUT -a ALLELES -o OUTPUT "

###
if [ -f "$lib_path"/run_PRIME.pl ]; then
	lib=$lib_path
else
	echo PRIME not found.
	exit 1;
fi

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
cat <<END
$usage
Mandatory parameters:
  -i, --input             Absolute or relative path to the input file (fasta format or list of peptides)
  -o, --output            Specify a file for the output
  -a, --allele            List of alleles to be considered, separated by comma (A0101,A2501,B0801,B1801)

Optional parameters:
  -mix, --MixMHCpred      Path of the MixMHCpred executable file (v2.2 or above)
END
	exit 0;
fi


while [ $# -gt 0 ]; do
	case $1 in
	    -i | --input) input=$2; shift 2;;
	    -o | --output) output_file=$2; shift 2;;
	    -a | --allele) alleles=$2; shift 2;;
	    -mix | --MixMHCpred) MixMHCpred=$2; shift 2;;
	    *) shift 1;;
	esac
done


input=`perl -e 'use Cwd "abs_path";print abs_path(shift)' $input`;
if [[ "$input" =~ " " ]]; then
    echo Spaces in input path are not supported
    exit 1;
fi
if [ ! -f $input ]; then
	echo Missing input file
	exit 1;
fi

if [ ! -n "$alleles" ]; then
	echo Missing alleles
	exit 1;
fi


dir=`pwd`

echo "" > $output_file
output_file=`perl -e 'use Cwd "abs_path";print abs_path(shift)' $output_file`;

if [[ "$output_file" =~ " " ]]; then
    echo Spaces in output path are not supported
    exit 1;
fi

if [[ "$output_file" =~ "*" ]]; then
    echo Stars in output path are not supported
    exit 1;
fi

if [[ "$output_file" == "" ]]; then
    echo Problem with output file - likely missing directory
    exit 1;
fi

#Check if MixMHCpred is available
if [ ! -n "$MixMHCpred" ]; then

    MixMHCpred=`which MixMHCpred`;
    if [ ! -n "$MixMHCpred" ]; then
	echo "MixMHCpred not in your path. Please manually enter the path to MixMHCpred in the input line as '-mix MIXMHCPRED_PATH' (version 3.0 or above).";
	exit 1;
    fi

fi

perl $lib_path/run_PRIME.pl --alleles $alleles --input $input --dir $dir --output $output_file --lib $lib_path --mix $MixMHCpred
